# configs/pipeline.yaml

steps:
  step1_ingestion:
    enabled: true
    script: "src/ingestion/document_ingestion.py"
    config: "configs/document_ingestion.yaml"
  step2_processing:
    enabled: true
    script: "src/preprocess/process_documents.py"
    config: "configs/process.yaml"
  step3_anonymization:
    enabled: false
    script: "src/anonymization/anonymizer.py"
    config: "configs/anonymization.yaml"
  step4_classification:
    enabled: true
    script: "src/classification/classify_documents.py"
    config: "configs/classification.yaml"
